### ISSUE TITLE
A question about using the joints positions and joints orientations at the same time

### ISSUE THREAD

**Issue by yuyujunjun** [electronicarts/character-motion-vaes#4]
The paper mentiones that use the joints position and orientation at the same time to represent a motion. However, I think one of them is able to represent a character adequately. 
Also, I noticed that the code render the character after the function set_joint_positions. I think it use the positions of each joint,  but I am not sure what role does each joint's orientation play. 
I would appreaciate it if you can reply!

**Comment by belinghy** [comment]
You're right.  The orientation of a bone can be determined by the adjacent joint xyz coordinates, except for end-effectors.  So most of the orientation features are redundant.  We found that using these redundant features improve the overall motion quality in our experiments.

**Comment by yuyujunjun** [comment]
Thank you very much!
