### ISSUE TITLE
reset() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by soomean** [electronicarts/character-motion-vaes#5]
Hello,
thank you for the great work!

While running `vae_motion/train_controller.py`,
An error shows up as below:

  logger.warn(
Traceback (most recent call last):
  File "train_controller.py", line 240, in <module>
    main()
  File "train_controller.py", line 206, in main
    obs = env.reset(reset_indices)
TypeError: reset() takes 1 positional argument but 2 were given

Can I ask how it would be fixed?

**Comment by soomean** [comment]
I resolved this issue.
In my version of the code, I needed to use the named argument for that.

I'll close this by myself.

Best,

**Comment by edentliang** [comment]
Hello, I got the same problem like yours, but I have no idea where is the issue. Can u give some hints? 

Thank you

**Comment by soomean** [comment]
Hi, @edentliang 
In my case, the error was gone by explicitly setting reset_indices with its keyword as  `obs = env.reset(indices=reset_indices)`.

**Comment by edentliang** [comment]
@soomean oh, it works. Thank you again. Very curious about the named argument, since I can't find that in the gym package
