### ISSUE TITLE
Question about calculating target angle in JoyStick env

### ISSUE THREAD

**Issue by heyuanYao-pku** [electronicarts/character-motion-vaes#6]
Hello, I have some qusetion about the target angle in mocap_env.py.

The defination of target angle is 
```python
target_angle = (
            torch.atan2(target_delta[:, 1], target_delta[:, 0]).unsqueeze(1)
            + self.root_facing
        )
```
which seems to be a relative angle plus current facing angle.

But in calculating the reward, you just calculate the cos of target angle instead of the cos of relative angle

```python
def calc_progress_reward(self):
        _, target_angle = self.get_target_delta_and_angle()
        direction_reward = target_angle.cos().add(-1)
        speed = self.next_frame[:, [0, 1]].norm(dim=1, keepdim=True)
        speed_reward = (self.target_speed_buf - speed).abs().mul(-1)
        return (direction_reward + speed_reward).exp()
````
Did I understand something wrong?

**Comment by belinghy** [comment]
Target angle is the angle to target in the character's reference frame.  When the character is directly facing the target, the angle should be 0, and so the reward should be maximize.

Hopefully this helps.  And please let me know I got anything wrong, it's been awhile.

**Comment by heyuanYao-pku** [comment]
Thanks a lot for your reply. While I'm still wondering should it be minus instead of plus when calculating the target angle？
```python
target_angle = (
            torch.atan2(target_delta[:, 1], target_delta[:, 0]).unsqueeze(1)
            + self.root_facing
        )
```

**Comment by belinghy** [comment]
You're right.  Normally, it should be minus instead of plus.  But when I was testing, I found root facing to always be inverted due to the way I was preprocessing data.  I was using a hacky way to convert y-axis up to z-axis up which mirrored the data.  In any case, it should be the angle to target to character space.

**Comment by heyuanYao-pku** [comment]
I see. It helps a lot and thanks very much！
