### ISSUE TITLE
What are the num_parallels for?

### ISSUE THREAD

**Issue by ameliacode** [electronicarts/character-motion-vaes#8]
Hi again. I am messing around with the code for months.
I did read the paper over and over again, seems like controller are for synthesizing motion.

So.. I have made my own version of environment to train the characters to compete each other.
and I have notice there is num_parallel variable which visualize numerous characters.

However, as it is on the code, it seems that action space dimension is only for single character unlike other things as root_history which includes dimension of num_parallel.

Is num_parallel variable exists just for training? I am confused..

**Comment by belinghy** [comment]
I'm glad to hear that you are extending our project, @ameliacode!

By "action space dimension", are you referring to these [two lines](https://github.com/electronicarts/character-motion-vaes/blob/d8ff62f3a9f7fd330ebd797df3e7f8f7ec7c3816/environments/mocap_envs.py#L108-L109)?  If yes, then this is just the standard way of defining the environment; and yes, it is only defined for the one character.

The environment returns a state array, its size is `(num_parallel, observation_size)`.  During training and inference, the array is passed through a network which convert state into actions, e.g., `(num_parallel, action_size)`.

**Comment by ameliacode** [comment]
soo....Is it possible to utilize or interpret num parallel as number of characters ?? (ex using root xz or root facing) or is the num parallel exists just for training?

I just want simplify my environment to two identical agents competiting in my case..

**Comment by belinghy** [comment]
Yes, they are the same, num parallel is number of characters.  With some changes to the environment, it is possible to have two agent competing together.

**Comment by ameliacode** [comment]
thanks for reply! it helped a lot
